### ISSUE TITLE
Incorrect fast bid auction result?

### ISSUE THREAD

**Issue by dlpierce** [boardgamers/powergrid#47]
The result of this fast bid auction seem incorrect to me. This is a recharged game on America with the fast bid option.

![Screenshot_20220721_122836](https://user-images.githubusercontent.com/105335/180266833-e69ec286-099f-4ac5-9f8a-8fec4ae1aee1.png)

Max bids are Green: $12, Purple: $11, Red: $10

I had expected the auction to be resolved like this, taking into account turn order:

1. Green places an initial bid of $10 on plant 10.
2. Purple bids $11, their max.
3. Red's max bid is $10, so they are out.
4. Green increases their bid to $12, their max.
5. Purple's max is exceeded so they are out.
6. Green wins and pays $12.

**Comment by LucasAMello** [comment]
Actually, Green's initial bid was for $12, in fast bid everyone bids once, there are no increases.
The bids are, as you said, Green: $12, Purple: $11, Red: $10.
First we see who's the winner of the auction, in this case it's Green.
Next, we see what's the amount Green needs to pay. Since Green is first on turn order, he just needs to match Purple's bid of $11.

**Comment by dlpierce** [comment]
Okay, thank you for the clarification.
